"""Build a cleaned full-product CLIP text index from listing metadata."""

import argparse
import json
import os
import re
import time
from pathlib import Path

import faiss
import numpy as np
import open_clip
import torch


CLIP_DIR = Path(r"F:\Clip")
SOURCE_INDEX_DIR = CLIP_DIR / "data" / "full_clip_index"
SOURCE_METADATA_PATH = SOURCE_INDEX_DIR / "products_full_meta.json"
PRICE_METADATA_PATH = SOURCE_INDEX_DIR / "products_full_prices.json"
MODEL_PATH = CLIP_DIR / "models" / "open_clip_pytorch_model.bin"
CHECKPOINT_PATH = CLIP_DIR / "data" / "yunqi_clip_training" / "last_checkpoint.pt"
OUTPUT_DIR = CLIP_DIR / "data" / "full_listing_index"
METADATA_PATH = OUTPUT_DIR / "products_listing_meta.json"
EMBEDDINGS_PATH = OUTPUT_DIR / "products_listing_embeddings.npy"
INDEX_PATH = OUTPUT_DIR / "products_listing.index"
PROGRESS_PATH = OUTPUT_DIR / "progress.json"
REPORT_PATH = OUTPUT_DIR / "cleaning_report.json"
MODEL_NAME = "ViT-B-32"
DEFAULT_BATCH_SIZE = 256
DEFAULT_SAVE_EVERY = 2048

STOP_WORDS = {
    "with",
    "for",
    "and",
    "the",
    "set",
    "pcs",
    "piece",
    "pieces",
    "pack",
    "new",
    "hot",
    "sale",
    "best",
    "high",
    "quality",
    "portable",
    "creative",
    "fashion",
    "women",
    "men",
    "kids",
    "girls",
    "boys",
    "home",
    "office",
    "outdoor",
    "indoor",
}


def parse_arguments():
    """Parse options for a resumable listing-index build."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument("--save-every", type=int, default=DEFAULT_SAVE_EVERY)
    parser.add_argument("--force-clean", action="store_true")
    return parser.parse_args()


def write_json_atomic(path, payload):
    """Write JSON through a temporary file and replace the target atomically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    temporary_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    last_error = None
    attempt = 0
    while attempt < 10:
        try:
            os.replace(temporary_path, path)
            return
        except PermissionError as error:
            last_error = error
            time.sleep(0.5)
        attempt += 1
    raise last_error


def clean_spaces(value):
    """Collapse noisy whitespace and remove invisible control characters."""
    text = str(value or "").replace("\u0000", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def looks_mojibake(value):
    """Detect obviously broken text so English listing can be preferred."""
    text = str(value or "")
    if not text:
        return False
    bad_count = 0
    for character in text:
        if character == "�":
            bad_count += 1
    return bad_count >= max(3, len(text) // 12)


def choose_listing_text(record):
    """Choose the cleanest searchable listing text from one product record."""
    title_en = clean_spaces(record.get("title_en", ""))
    title_cn = clean_spaces(record.get("title_cn", ""))
    title = clean_spaces(record.get("title", ""))
    if title_en:
        return title_en
    if title and not looks_mojibake(title):
        return title
    if title_cn and not looks_mojibake(title_cn):
        return title_cn
    return title_en or title or title_cn


def normalize_for_exact_dedupe(value):
    """Build a strict title key for exact duplicate removal."""
    text = clean_spaces(value).lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def make_family_key(value):
    """Build a coarse key used later to avoid same-looking Top results."""
    normalized = normalize_for_exact_dedupe(value)
    tokens = normalized.split(" ")
    kept_tokens = []
    for token in tokens:
        if len(token) <= 2:
            continue
        if token in STOP_WORDS:
            continue
        if token.isdigit():
            continue
        kept_tokens.append(token)
    unique_tokens = []
    for token in kept_tokens:
        if token not in unique_tokens:
            unique_tokens.append(token)
    if len(unique_tokens) <= 2:
        return normalized[:80]
    return " ".join(unique_tokens[:10])


def load_source_products():
    """Load the existing full product metadata generated by the image index."""
    if not SOURCE_METADATA_PATH.exists():
        raise FileNotFoundError(f"Missing source metadata: {SOURCE_METADATA_PATH}")
    return json.loads(SOURCE_METADATA_PATH.read_text(encoding="utf-8"))


def clean_products(raw_products):
    """Drop unusable listings and exact duplicate listing records."""
    cleaned_products = []
    seen_titles = set()
    seen_ids = set()
    dropped_short = 0
    dropped_duplicate = 0
    dropped_missing = 0
    for raw_product in raw_products:
        product_id = str(raw_product.get("id", "")).strip()
        listing_text = choose_listing_text(raw_product)
        exact_key = normalize_for_exact_dedupe(listing_text)
        if not product_id or not listing_text:
            dropped_missing += 1
            continue
        if len(exact_key) < 8:
            dropped_short += 1
            continue
        if product_id in seen_ids or exact_key in seen_titles:
            dropped_duplicate += 1
            continue
        product = raw_product.copy()
        product["title"] = listing_text
        product["listing_text"] = listing_text
        product["listing_key"] = exact_key
        product["family_key"] = make_family_key(listing_text)
        product["img_url"] = f"/listing-images/{product_id}.jpg"
        cleaned_products.append(product)
        seen_ids.add(product_id)
        seen_titles.add(exact_key)
    report = {
        "source": len(raw_products),
        "kept": len(cleaned_products),
        "dropped_missing": dropped_missing,
        "dropped_short": dropped_short,
        "dropped_duplicate": dropped_duplicate,
        "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    return cleaned_products, report


def load_or_create_clean_products(force_clean):
    """Reuse cleaned metadata unless a fresh cleaning pass is requested."""
    if METADATA_PATH.exists() and not force_clean:
        return json.loads(METADATA_PATH.read_text(encoding="utf-8"))
    raw_products = load_source_products()
    cleaned_products, report = clean_products(raw_products)
    write_json_atomic(METADATA_PATH, cleaned_products)
    write_json_atomic(REPORT_PATH, report)
    return cleaned_products


def load_model():
    """Load the trained CLIP text tower on CPU."""
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"Missing base model: {MODEL_PATH}")
    if not CHECKPOINT_PATH.exists():
        raise FileNotFoundError(f"Missing trained checkpoint: {CHECKPOINT_PATH}")
    device = torch.device("cpu")
    model, _, _ = open_clip.create_model_and_transforms(
        MODEL_NAME,
        pretrained=str(MODEL_PATH),
    )
    checkpoint = torch.load(CHECKPOINT_PATH, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model"])
    model = model.to(device)
    model.eval()
    tokenizer = open_clip.get_tokenizer(MODEL_NAME)
    return model, tokenizer, device


def load_progress(total):
    """Read the last completed text embedding count for resume."""
    if not PROGRESS_PATH.exists():
        return 0
    progress = json.loads(PROGRESS_PATH.read_text(encoding="utf-8"))
    if int(progress.get("total", total)) != total:
        raise RuntimeError("Existing listing progress does not match cleaned metadata")
    return max(0, min(total, int(progress.get("completed", 0))))


def open_embedding_memmap(total, dimension):
    """Create or reopen the text embedding memmap."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if EMBEDDINGS_PATH.exists():
        embedding_matrix = np.lib.format.open_memmap(EMBEDDINGS_PATH, mode="r+")
        if embedding_matrix.shape != (total, dimension):
            raise RuntimeError("Existing listing embedding matrix shape mismatch")
        return embedding_matrix
    return np.lib.format.open_memmap(
        EMBEDDINGS_PATH,
        mode="w+",
        dtype="float32",
        shape=(total, dimension),
    )


def restore_faiss_index(embedding_matrix, completed, dimension):
    """Rebuild an in-memory FAISS index from completed text vectors."""
    index = faiss.IndexFlatIP(dimension)
    chunk_size = 8192
    start_index = 0
    while start_index < completed:
        end_index = min(start_index + chunk_size, completed)
        index.add(np.asarray(embedding_matrix[start_index:end_index], dtype="float32"))
        start_index = end_index
    return index


def write_faiss_index_file(index, path):
    """Write a FAISS index through Python bytes so Windows Unicode paths stay valid."""
    serialized_index = faiss.serialize_index(index)
    path.write_bytes(serialized_index.tobytes())


def encode_text_batch(model, tokenizer, texts, device):
    """Encode one batch of listing strings with the trained text tower."""
    tokens = tokenizer(texts).to(device)
    with torch.inference_mode():
        features = model.encode_text(tokens)
        features = features / features.norm(dim=-1, keepdim=True)
    return features.cpu().numpy().astype("float32")


def encode_products(products, model, tokenizer, device, batch_size, save_every):
    """Encode cleaned listings and print live throughput."""
    dimension = int(model.text_projection.shape[1])
    total = len(products)
    completed = load_progress(total)
    embedding_matrix = open_embedding_memmap(total, dimension)
    index = restore_faiss_index(embedding_matrix, completed, dimension)
    started_at = time.perf_counter()
    while completed < total:
        batch_end = min(completed + batch_size, total)
        texts = []
        product_index = completed
        while product_index < batch_end:
            texts.append(products[product_index]["listing_text"])
            product_index += 1
        batch_features = encode_text_batch(model, tokenizer, texts, device)
        embedding_matrix[completed:batch_end] = batch_features
        index.add(batch_features)
        completed = batch_end
        if completed % save_every < batch_size or completed >= total:
            embedding_matrix.flush()
            write_json_atomic(
                PROGRESS_PATH,
                {
                    "completed": completed,
                    "total": total,
                    "status": "building",
                    "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
                },
            )
        elapsed = time.perf_counter() - started_at
        rate = completed / max(elapsed, 1e-6)
        eta_minutes = (total - completed) / max(rate, 1e-6) / 60
        print(
            "listing_embedding",
            completed,
            "/",
            total,
            "rate",
            f"{rate:.2f}/s",
            "eta_minutes",
            f"{eta_minutes:.1f}",
            flush=True,
        )
    return embedding_matrix, index


def write_final_outputs(products, embedding_matrix, index):
    """Publish the finished listing index without touching the image index."""
    embedding_matrix.flush()
    temporary_index_path = INDEX_PATH.with_suffix(INDEX_PATH.suffix + ".tmp")
    write_faiss_index_file(index, temporary_index_path)
    os.replace(temporary_index_path, INDEX_PATH)
    write_json_atomic(METADATA_PATH, products)
    write_json_atomic(
        PROGRESS_PATH,
        {
            "completed": len(products),
            "total": len(products),
            "status": "complete",
            "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        },
    )
    return index.ntotal


def main():
    """Run the full cleaned listing-index build."""
    arguments = parse_arguments()
    products = load_or_create_clean_products(arguments.force_clean)
    model, tokenizer, device = load_model()
    print(
        "listing_index_start",
        json.dumps(
            {
                "device": str(device),
                "products": len(products),
                "batch_size": arguments.batch_size,
                "output_dir": str(OUTPUT_DIR),
            },
            ensure_ascii=False,
        ),
        flush=True,
    )
    embedding_matrix, index = encode_products(
        products,
        model,
        tokenizer,
        device,
        max(1, arguments.batch_size),
        max(1, arguments.save_every),
    )
    vector_count = write_final_outputs(products, embedding_matrix, index)
    print(
        "listing_index_complete",
        json.dumps(
            {
                "vectors": vector_count,
                "dimension": int(embedding_matrix.shape[1]),
                "index": str(INDEX_PATH),
            },
            ensure_ascii=False,
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
